SELECT
d.DEPARTMENT_NAME AS Departamento,
j.JOB_TITLE AS Cargo,
e.SALARY AS Salario
FROM
HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN HR.JOBS j
ON e.JOB_ID = j.JOB_ID
WHERE d.DEPARTMENT_NAME IS NOT NULL
ORDER BY
d.DEPARTMENT_NAME ASC,
e.SALARY DESC,
j.JOB_TITLE