SELECT
r.REGION_NAME AS Continente,
c.COUNTRY_NAME AS País,
l.STATE_PROVINCE AS Estado,
l.CITY AS Cidade,
d.DEPARTMENT_NAME AS Departamento,
e.SALARY AS Salario
FROM
HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d
ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS l
ON d.LOCATION_ID = l.LOCATION_ID
LEFT JOIN HR.COUNTRIES c
ON l.COUNTRY_ID = c.COUNTRY_ID
LEFT JOIN HR.REGIONS r
ON c.REGION_ID = r.REGION_ID
WHERE d.DEPARTMENT_NAME IS NOT NULL
GROUP BY
r.REGION_NAME,
c.COUNTRY_NAME,
l.STATE_PROVINCE,
l.CITY,
d.DEPARTMENT_NAME,
e.SALARY
ORDER BY
r.REGION_NAME ASC,
c.COUNTRY_NAME ASC,
l.STATE_PROVINCE ASC,
l.CITY ASC,
e.SALARY DESC